program: run.py
method: grid
metric:
  goal: maximize
  name: Average Precision
parameters:
  path:
    value: data/self-data.csv
  batch_size: 
    values: [4, 8, 12, 16]
  img_size: 
    value: 640
  backbone:
    value: efficientdet_q1
  max_epochs:
    value: 100
  predict_confidence_thres:
    values: [0.5, 0.65, 0.8]
  lr: 
    values: [0.01, 0.001, 0.0001, 0.00001]
  iou_thres: 
    values: [0.5, 0.65, 0.8]
  optimizer:
    values: ['AdamW', 'SGD']
command:
  - ${env}
  - python3
  - ${program}

project: EfficientDetQ1 Sweep
name: EfficientDet Q1