program: run.py
method: grid
metric:
  goal: maximize
  name: Average Precision
parameters:
  path:
    value: data/self-data.csv
  batch_size: 
    value: [2,4,6,8]
  img_size: 
    value: 1024
  backbone:
    value: efficientdetv2_ds
  max_epochs:
    value: 300
  predict_confidence_thres:
    value: [0.4, 0.5, 0.6, 0.7, 0.8]
  lr: 
    value: [0.01, 0.001, 0.0001, 0.00001]
  iou_thres: 
    value: [0.4, 0.5, 0.6, 0.7, 0.8]
  optimizer:
    value: ['AdamW', 'SGD', 'Adam']
command:
  - ${env}
  - python3
  - ${program}

project: EfficientDetV2 DS Sweep
name: EfficientDetV2 DS