project: EffDet (tf_efficientdet_d2 backbone)
batch_size: 1
img_size: 768
backbone: tf_efficientdet_d2
max_epochs: 1500
predict_confidence_thres: 0.6
lr: 0.0002
iou_thres: 0.6
optimizer: 'AdamW'
name: EfficientDetD2
