wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.1
    start_time: 1672633180.00464
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 7
      - 23
      4: 3.9.1
      5: 0.13.7
      8:
      - 5
